name: build

on: [push, pull_request]

jobs:
  run-test:
    name: Runs the tests
    runs-on: macos-11
    strategy:
      matrix:
        destination: [
          'iOS Simulator,name=iPhone 11'
        ]
        swift-version: [5.0]
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true
      - name: Run tests
        env:
          DESTINATION: platform=${{ matrix.destination }}
          SWIFT_VERSION: ${{ matrix.swift-version }}
        run: bundle exec fastlane test_ci
